"""add_file_versioning_and_metadata

Revision ID: 629f01962caa
Revises: 003_add_oauth_accounts
Create Date: 2026-01-02 15:30:45.118229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '629f01962caa'
down_revision: Union[str, None] = '003_add_oauth_accounts'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

