"""Add file history and comments tables

Revision ID: 9be502d1530e
Revises: 629f01962caa
Create Date: 2026-01-02 20:18:30.816706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9be502d1530e'
down_revision: Union[str, None] = '629f01962caa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folder_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folder_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('parent_comment_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['folder_comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_folder_comments_created_at'), 'folder_comments', ['created_at'], unique=False)
    op.create_index(op.f('ix_folder_comments_folder_id'), 'folder_comments', ['folder_id'], unique=False)
    op.create_index(op.f('ix_folder_comments_id'), 'folder_comments', ['id'], unique=False)
    op.create_index(op.f('ix_folder_comments_user_id'), 'folder_comments', ['user_id'], unique=False)
    op.create_table('folder_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folder_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('CREATED', 'UPDATED', 'RENAMED', 'MOVED', 'DELETED', 'RESTORED', 'SHARED', 'UNSHARED', 'DOWNLOADED', 'VIEWED', name='actiontype'), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('extra_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_folder_history_created_at'), 'folder_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_folder_history_folder_id'), 'folder_history', ['folder_id'], unique=False)
    op.create_index(op.f('ix_folder_history_id'), 'folder_history', ['id'], unique=False)
    op.create_index(op.f('ix_folder_history_user_id'), 'folder_history', ['user_id'], unique=False)
    op.create_table('file_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('parent_comment_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['file_comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_comments_created_at'), 'file_comments', ['created_at'], unique=False)
    op.create_index(op.f('ix_file_comments_file_id'), 'file_comments', ['file_id'], unique=False)
    op.create_index(op.f('ix_file_comments_id'), 'file_comments', ['id'], unique=False)
    op.create_index(op.f('ix_file_comments_user_id'), 'file_comments', ['user_id'], unique=False)
    op.create_table('file_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('CREATED', 'UPDATED', 'RENAMED', 'MOVED', 'DELETED', 'RESTORED', 'SHARED', 'UNSHARED', 'DOWNLOADED', 'VIEWED', name='actiontype'), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('extra_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_history_created_at'), 'file_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_file_history_file_id'), 'file_history', ['file_id'], unique=False)
    op.create_index(op.f('ix_file_history_id'), 'file_history', ['id'], unique=False)
    op.create_index(op.f('ix_file_history_user_id'), 'file_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_history_user_id'), table_name='file_history')
    op.drop_index(op.f('ix_file_history_id'), table_name='file_history')
    op.drop_index(op.f('ix_file_history_file_id'), table_name='file_history')
    op.drop_index(op.f('ix_file_history_created_at'), table_name='file_history')
    op.drop_table('file_history')
    op.drop_index(op.f('ix_file_comments_user_id'), table_name='file_comments')
    op.drop_index(op.f('ix_file_comments_id'), table_name='file_comments')
    op.drop_index(op.f('ix_file_comments_file_id'), table_name='file_comments')
    op.drop_index(op.f('ix_file_comments_created_at'), table_name='file_comments')
    op.drop_table('file_comments')
    op.drop_index(op.f('ix_folder_history_user_id'), table_name='folder_history')
    op.drop_index(op.f('ix_folder_history_id'), table_name='folder_history')
    op.drop_index(op.f('ix_folder_history_folder_id'), table_name='folder_history')
    op.drop_index(op.f('ix_folder_history_created_at'), table_name='folder_history')
    op.drop_table('folder_history')
    op.drop_index(op.f('ix_folder_comments_user_id'), table_name='folder_comments')
    op.drop_index(op.f('ix_folder_comments_id'), table_name='folder_comments')
    op.drop_index(op.f('ix_folder_comments_folder_id'), table_name='folder_comments')
    op.drop_index(op.f('ix_folder_comments_created_at'), table_name='folder_comments')
    op.drop_table('folder_comments')
    # ### end Alembic commands ###

